DEFAULT:
  JWT_KEY: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

server:
  port: 8081
  servlet:
    context-path: /identity
spring:
  jackson:
    time-zone: Asia/Ho_Chi_Minh
  data:
    redis:
      host: 203.145.46.242
      port: 6379
      password: Pickleball@123
  datasource:
    url: jdbc:mysql://203.145.46.242:3306/pickleball?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: Pickleball@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  signerKey: ${JWT_KEY:${DEFAULT.JWT_KEY}}
  valid-duration: 3600 # in second
  refreshable-duration: 3600 # in seconds

payment:
  url : https://payment-gateway.hyperlogy.com/api
  create_qr: /payment/auth/protected/create_qr
  check_sum: 20fbb136-cc71-4a51-99eb-634c86ec1ce5
  api_key: 2a903a68-461d-43ea-b66e-4af7253e40fd
  client_id: fd342a17-7fb2-4df1-b907-c0004583746a

court_service:
  url_service : http://203.145.46.242:8080/api/court
  update_bookingSlot: /public/booking_slot/update